### ISSUE TITLE
Miele integration

### ISSUE THREAD

**Issue by mweinelt** [graham33/nur-packages#56]
Found https://github.com/astrandb/miele to be the better integration. Not sure if you found it or ruled it out yet. Using it with a dishwasher.

**Comment by graham33** [comment]
Thanks, no I didn't see that. The one I'm using seems to be ok for the basics, but I haven't done any real automations yet. I'll look at the one you linked and see how it compares.

**Comment by graham33** [comment]
This one seems better, agreed!

**Comment by graham33** [comment]
Closing out

**Comment by graham33** [comment]
This one seems better, agreed!
